AWSTemplateFormatVersion: 2010-09-09

Description: |
  Create static website for kittens carousel
  
# Parameters:
  
Resources:

  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: KittensSecGroup
      GroupDescription: Allow SSH and HTTP # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  rWebServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - Key: Name
          Value: tommy-carousel-webserver
      ImageId: ami-066784287e358dad1
      InstanceType: t2.micro
      KeyName: ec2-ssh-key
      SecurityGroupIds: 
      - !GetAtt rSecurityGroup.GroupId
      UserData: "String"

  
# Outputs: